### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by jasonhildebrand** [nlgio/w4py3-middlekit#5]
I was able to run the test suite today, and got these results using MySQL:

```
RESULTS
-------
     succeeded MKBasic.mkmodel
     succeeded MKNone.mkmodel 
     succeeded MKString.mkmodel
*** FAILED *** MKDateTime.mkmodel
     succeeded MKEnums.mkmodel   
     succeeded MKDefaultMinMax.mkmodel
*** FAILED *** MKTypeValueChecking.mkmodel
     succeeded MKInheritance.mkmodel
     succeeded MKInheritanceAbstract.mkmodel
     succeeded MKList.mkmodel
     succeeded MKObjRef.mkmodel
     succeeded MKObjRefReuse.mkmodel
     succeeded MKDelete.mkmodel
     succeeded MKDeleteMark.mkmodel
     succeeded MKBackRef.mkmodel   
     succeeded MKClone.mkmodel  
*** FAILED *** MKDump.mkmodel 
     succeeded MKRefresh.mkmodel
     succeeded MKMultipleStores.mkmodel
     succeeded MKMultipleThreads.mkmodel
     succeeded MKModelInh1.mkmodel
     succeeded MKModelInh2.mkmodel
     succeeded MKModelInh3.mkmodel
       skipped MKExcel.mkmodel    
```

Is this different than what you have seen?  I will investigate further to see if I can determine the cause of the failures.

**Comment by jasonhildebrand** [comment]
I am not able to reproduce the MKDateTime failure.  The original traceback I got was:

```
Traceback (most recent call last):                                       
  File "TestDesign.py", line 61, in <module>
    test(sys.argv[1], sys.argv[2])                                      
  File "TestDesign.py", line 43, in test
    Generate().main(command)
  File "/src/w4py3-middlekit/webware/MiddleKit/Design/Generate.py", line 52, in main
    outdir=outdir)
  File "/src/w4py3-middlekit/webware/MiddleKit/Design/Generate.py", line 130, in generate
    generator.generate(outdir)
  File "/src/w4py3-middlekit/webware/MiddleKit/Design/PythonGenerator.py", line 19, in generate
    self._model.writePy(self, dirname)                                                         
  File "/src/w4py3-middlekit/webware/MiddleKit/Design/PythonGenerator.py", line 37, in writePy
    klass.writePy(generator, filename)                                                        
  File "/src/w4py3-middlekit/webware/MiddleKit/Design/PythonGenerator.py", line 55, in writePy
    self._writePy(generator, out)                                                             
  File "/src/w4py3-middlekit/webware/MiddleKit/Design/PythonGenerator.py", line 80, in _writePy
    self.writePyClassDef()                                                                     
  File "/src/w4py3-middlekit/webware/MiddleKit/Design/PythonGenerator.py", line 134, in writePyClassDef
    self.writePyAccessors()                                                                            
  File "/src/w4py3-middlekit/webware/MiddleKit/Design/PythonGenerator.py", line 167, in writePyAccessors
    attr.writePyAccessors(out)                                                                          
  File "/src/w4py3-middlekit/webware/MiddleKit/Design/PythonGenerator.py", line 200, in writePyAccessors
    self.writePySet(out)                                                                                
  File "/src/w4py3-middlekit/webware/MiddleKit/Design/PythonGenerator.py", line 215, in writePySet
    self.writePySetChecks(out)                                                                    
  File "/src/w4py3-middlekit/webware/MiddleKit/Design/PythonGenerator.py", line 505, in writePySetChecks
    DateAttr.mixInSuperWritePySetChecks(self, out)                                                      
AttributeError: type object 'DateAttr' has no attribute 'mixInSuperWritePySetChecks'
>> ABOUT TO EXIT WITH CODE 1                                                        
```

I think this was probably due to some paths not be set up correctly in my environment.  In any case it is passing reliably now - I have run it multiple times.

**Comment by nlgio** [comment]
about the failed MKTypeValueChecking, that is known and explained in 
https://github.com/nlgio/w4py3-middlekit/issues/1#issuecomment-565855965
we can exclude it from the TestSuite in line 37 by adding bar to skipAttrs
`typeErrors(f, 1, 'bar b i l f'.split())`


> 
> Is this different than what you have seen? I will investigate further to see if I can determine the cause of the failures.

**Comment by nlgio** [comment]
about the failed MKDump which is unexpected. The test case is to make a diff between Samples.csv and what was later dumped out. I never looked into because it always succeeded. Now,  I can see 2 things, first the Dump is not in the same order as that what was feeded in but  the parts in the dump are still the same. Then the result code from the applied diff command gets shifted to "ok" MKDump/TestSamples line 10 . Thats looks like to be the reason why this Testcase  succeeds which btw shouldnt be. The same for python2-MiddleKit variant. Whats to do now?, my assumption is that Your  diff exits with an result code >255, so the issue is with the TestCase

**Comment by jasonhildebrand** [comment]
Yeah, the dump is in a different order on my end, too.  The shifting of the return value is correct for Posix, but not for Windows (are you running on Windows?).

I have some time today - I will see if I can get dump to produce output in a consistent order.  That would fix this test.  I'll also fix up the return code checking to be compatible with Windows.

**Comment by jasonhildebrand** [comment]
I submitted PR #6 to fix MKDump.

**Comment by jasonhildebrand** [comment]
I think these are all dealt with now -- closing.
